details:
- algorithm:
    aligner: bwa
    svcaller:
    - manta
    variant_regions: keep:8454ebf775359dbccecdc5193c0442c3+974/automated/variant_regions-bam.bed
    variantcaller:
    - vardict
  analysis: variant2
  description: Test2
  files:
  - keep:8454ebf775359dbccecdc5193c0442c3+974/100326_FC6107FAAXX/6_100326_FC6107FAAXX.bam
  genome_build: hg19
  metadata:
    batch: b1
    phenotype: normal
- algorithm:
    aligner: bwa
    svcaller:
    - manta
    validate: keep:8454ebf775359dbccecdc5193c0442c3+974/reference_material/7_100326_FC6107FAAXX-grade.vcf
    validate_regions: keep:8454ebf775359dbccecdc5193c0442c3+974/automated/variant_regions-bam.bed
    variant_regions: keep:8454ebf775359dbccecdc5193c0442c3+974/automated/variant_regions-bam.bed
    variantcaller:
    - vardict
  analysis: variant2
  description: Test1
  files:
  - keep:8454ebf775359dbccecdc5193c0442c3+974/100326_FC6107FAAXX/7_100326_FC6107FAAXX.bam
  genome_build: hg19
  metadata:
    batch: b1
    phenotype: tumor
fc_name: arvados_testcwl
upload:
  dir: ../final
